#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nVous devez avoir les droits super-utilisateur pour executer $0"
	exit 1;
fi

echo "Installation des dépendances"
pip3 install paho-mqtt
pip3 install websocket-client
pip3 install python-socketio==4.6.1
pip3 install python-engineio==3.14.2
echo "Copie des fichiers necessaires"
if [ ! -d "/opt/maestro/" ];then
	mkdir /opt/maestro/
	chown -R $USER /opt/maestro/
	chmod -R 0755 /opt/maestro/
fi

cp _config_.py /opt/maestro
cp _data_.py /opt/maestro
cp maestro.py /opt/maestro

echo "Creation du directory de log"
if [ ! -d "/var/log/maestro/" ];then
	mkdir /var/log/maestro/
	chown -R $USER /var/log/maestro/
	chmod -R 0755 /var/log/maestro/
fi

python3 /opt/maestro/maestro.py
